### ISSUE TITLE
:VimBootstrapUpdate fails with fish-shell

### ISSUE THREAD

**Issue by andys8** [avelino/vim-bootstrap-updater#15]
- Vim bootstrap version(number in first line): b990cad 
- Operating system: Ubuntu 16.04 xenial
- Vim/Nvim version: 8.1 (2018 May 18, compiled Oct 22 2018 12:20:21)
- Languages: Elm, JS, .. 
- Shell: [Fish](https://fishshell.com)

## Description

Running `:VimBootstrapUpdate` will print:
```shell
fish: Unknown command 'rl -fLso /home/ascharf/.vimrc http://vim-bootstrap.com/generate.vim --data langs=elm&langs=html&langs=javascript&editor=vim'
fish: 
\curl -fLso /home/user/.vimrc http://vim-bootstrap.com/generate.vim --data langs=elm\&langs=html\&langs=javascript\&editor=vim
^
```

I guess it is related to this line and `fish` won't accept `!\curl`.
https://github.com/avelino/vim-bootstrap-updater/blob/be6ac7be1898d506ab6328fee74b578def9212b6/plugin/vim_bootstrap_updater.vim#L9

**Comment by avelino** [comment]
Can you fix it (PR)?

**Comment by cassiobotaro** [comment]
Thank you @andys8 !
